# Generated by Django 3.1.6 on 2023-06-26 17:57

from django.db import migrations, models
import document.enums
import document.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[(document.models.LanguageChoice['DE'], 'German'), (document.models.LanguageChoice['EN'], 'English'), (document.models.LanguageChoice['CN'], 'Chinese'), (document.models.LanguageChoice['ES'], 'Spanish')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai', models.IntegerField()),
                ('dtype', models.CharField(choices=[(document.enums.DocType['AN'], 'Analytical Data'), (document.enums.DocType['CO'], 'Compliance'), (document.enums.DocType['CI'], 'Correspondence-Internal'), (document.enums.DocType['CR'], 'Correspondence-Received'), (document.enums.DocType['CS'], 'Correspondence-Sent'), (document.enums.DocType['FI'], 'Financial'), (document.enums.DocType['FO'], 'Forms'), (document.enums.DocType['LE'], 'Legal'), (document.enums.DocType['PE'], 'Permits'), (document.enums.DocType['PL'], 'Plans'), (document.enums.DocType['RE'], 'Reports'), (document.enums.DocType['OT'], 'Other')], default=document.enums.DocType['OT'], max_length=2)),
                ('dsubtype', models.CharField(choices=[(document.enums.DocSubType['AD'], 'ADVF'), (document.enums.DocSubType['AG'], 'Agreement/Contract'), (document.enums.DocSubType['AI'], 'Air'), (document.enums.DocSubType['AN'], 'Annual'), (document.enums.DocSubType['AP'], 'Application'), (document.enums.DocSubType['AS'], 'Assessment/Investigation'), (document.enums.DocSubType['BE'], 'Below Reportable Quantity Event'), (document.enums.DocSubType['CE'], 'Certificate/License/Registration'), (document.enums.DocSubType['CR'], 'Confidentiality Request'), (document.enums.DocSubType['CA'], 'Corrective Action'), (document.enums.DocSubType['DM'], 'DMR'), (document.enums.DocSubType['DR'], 'Draft Permit'), (document.enums.DocSubType['FE'], 'Fee Collection'), (document.enums.DocSubType['FP'], 'Final Permit'), (document.enums.DocSubType['FA'], 'Financial Assurance'), (document.enums.DocSubType['GR'], 'Green Cards'), (document.enums.DocSubType['HE'], 'Hearing Request'), (document.enums.DocSubType['ID'], 'ID-Generator Notification'), (document.enums.DocSubType['IC'], 'Incident'), (document.enums.DocSubType['IS'], 'Inspection'), (document.enums.DocSubType['IN'], 'Invoice'), (document.enums.DocSubType['JU'], 'Judgment/Decision/Order'), (document.enums.DocSubType['MA'], 'Manifest'), (document.enums.DocSubType['ME'], 'Meeting'), (document.enums.DocSubType['MD'], 'Modifications'), (document.enums.DocSubType['MO'], 'Monitoring'), (document.enums.DocSubType['NA'], 'Name/Owner Change'), (document.enums.DocSubType['NE'], 'NetDMR Subscriber Agreement'), (document.enums.DocSubType['NC'], 'Noncompliance'), (document.enums.DocSubType['NM'], 'Note/Memo'), (document.enums.DocSubType['NO'], 'Notice'), (document.enums.DocSubType['NF'], 'Notifications'), (document.enums.DocSubType['OR'], 'Order'), (document.enums.DocSubType['PE'], 'Penalty'), (document.enums.DocSubType['PU'], 'Public Notice'), (document.enums.DocSubType['QU'], 'Quarterly'), (document.enums.DocSubType['RF'], 'Reference Materials'), (document.enums.DocSubType['RT'], 'Returned Mail'), (document.enums.DocSubType['SM'], 'Semi-Annual'), (document.enums.DocSubType['ST'], 'Settlement'), (document.enums.DocSubType['TE'], 'Testing'), (document.enums.DocSubType['TR'], 'Trust Fund'), (document.enums.DocSubType['VA'], 'Variances/Exemptions'), (document.enums.DocSubType['WA'], 'Warning Letters'), (document.enums.DocSubType['OT'], 'Other')], default=document.enums.DocSubType['OT'], max_length=2)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('media', models.CharField(choices=[(document.enums.Media['AC'], 'Accident Prevention'), (document.enums.Media['AI'], 'Air Quality'), (document.enums.Media['AS'], 'Asbestos'), (document.enums.Media['BI'], 'Biosolids'), (document.enums.Media['GR'], 'Ground Water'), (document.enums.Media['HA'], 'Hazardous Waste'), (document.enums.Media['IN'], 'Inactive & Abandoned Sites'), (document.enums.Media['LE'], 'Lead'), (document.enums.Media['MU'], 'Multi-Media'), (document.enums.Media['NO'], 'Non-Applicable'), (document.enums.Media['RA'], 'Radiation'), (document.enums.Media['SO'], 'Solid Waste'), (document.enums.Media['SU'], 'Surface Water'), (document.enums.Media['UN'], 'Underground Storage Tanks'), (document.enums.Media['WA'], 'Waste Tire'), (document.enums.Media['OT'], 'Other')], default=document.enums.Media['OT'], max_length=2)),
                ('dfunction', models.CharField(choices=[(document.enums.DocFunction['AG'], 'Agency Governance'), (document.enums.DocFunction['AE'], 'Air Emissions Inventory'), (document.enums.DocFunction['AM'], 'Air Modeling'), (document.enums.DocFunction['AA'], 'Air Monitoring and Analysis'), (document.enums.DocFunction['AP'], 'Air Planning'), (document.enums.DocFunction['AS'], 'Air Stack and Tank Testing'), (document.enums.DocFunction['CH'], 'Chemical Accident Prevention'), (document.enums.DocFunction['EN'], 'Enforcement'), (document.enums.DocFunction['FI'], 'Financial'), (document.enums.DocFunction['IE'], 'Incidents - Emergency'), (document.enums.DocFunction['IN'], 'Incidents - Non-Emergency'), (document.enums.DocFunction['IF'], 'Information Services'), (document.enums.DocFunction['IS'], 'Inspections'), (document.enums.DocFunction['LE'], 'Legal'), (document.enums.DocFunction['OF'], 'Office of the Secretary (OSEC)'), (document.enums.DocFunction['OU'], 'Outreach'), (document.enums.DocFunction['PS'], 'Permit Support Services'), (document.enums.DocFunction['PE'], 'Permits'), (document.enums.DocFunction['RA'], 'Radiological Services'), (document.enums.DocFunction['RE'], 'Remediation Services'), (document.enums.DocFunction['SI'], 'Single Point of Contact (SPOC)'), (document.enums.DocFunction['UN'], 'Unassigned'), (document.enums.DocFunction['US'], 'Underground Storage Tanks'), (document.enums.DocFunction['WA'], 'Water Quality Standards and Assessment'), (document.enums.DocFunction['OT'], 'Other')], default=document.enums.DocFunction['OT'], max_length=2)),
                ('num_pages', models.IntegerField()),
                ('converted_text', models.TextField()),
            ],
        ),
    ]
