# Generated by Django 3.2 on 2023-07-07 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20230623_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='last_complainer_run',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
