# Generated by Django 3.1.6 on 2023-05-10 15:15

from django.db import migrations, models
import django.utils.timezone
import transcribe.models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcribe',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='transcribe',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transcribe',
            name='title',
        ),
        migrations.AddField(
            model_name='transcribe',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=transcribe.models.user_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transcribe',
            name='transcription',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
