# Generated by Django 3.1.6 on 2023-05-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0002_auto_20230510_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcribe',
            name='request_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
