# Generated by Django 3.1.6 on 2023-05-10 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0003_transcribe_request_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcribe',
            name='file',
        ),
        migrations.RemoveField(
            model_name='transcribe',
            name='transcription',
        ),
    ]
