# Generated by Django 3.2 on 2023-08-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_date', models.DateTimeField(auto_now=True)),
                ('submission_data', models.JSONField()),
                ('is_manual_run', models.BooleanField()),
            ],
        ),
    ]
